spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: arinamoiseeva321@gmail.com
    password: zehrgpouevhhgklz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8081